# Compatibility upgrade hook for grub2
#
# This file is part of cOS and will get reset during upgrades.
#
# Before you change this file manually,
# consider copying this file to /usr/local/cloud-config or
# copy the file with a prefix starting by 90, e.g. /oem/91_custom.yaml
name: "Adapt grub2 configuration on updates"
stages:
  after-upgrade-chroot:
    - name: "Install grub updater in OEM"
      commands:
      - |
        hook="/system/oem/01_upgrade_grub_hook.yaml"

        if mountpoint -q /oem; then
          [ -f "${hook}" ] || exit 0
          cp "${hook}" /oem
        fi
  after-upgrade.before:
    - name: "Check upgrade is needed"
      commands:
      - |
        original="/etc/cos/grub.cfg"
        new="/run/cos/transition${original}"
        current="/run/cos/state/grub2/grub.cfg"
        if [ ! -f "${current}" ]; then
          current="/run/initramfs/cos-state/grub2/grub.cfg"
        fi

        [ -f "${current}" ] || exit 1
        [ -f "${original}" ] || exit 1
        [ -f "${new}" ] || exit 1

        if ! cmp -s "${current}" "${original}"; then
          2>&1 echo "Customized grub.cfg detected! No grub upgrade is done"
          2>&1 echo "Manually adjusting grub.cfg is likely to be required to boot upgraded OS"
          exit 1
        fi

        if ! cmp -s "${current}" "${new}"; then
          echo "1" > "/run/cos/grub_update_needed"
        fi
  after-upgrade.after:
    - if: '[ -f "/oem/01_upgrade_grub_hook.yaml" ]'
      name: "Uninstall hook from OEM"
      commands:
      - |
        rm /oem/01_upgrade_grub_hook.yaml
  after-install:
    - &grubenv
      name: "Set grub env variables"
      commands:
      - |
        statemnt="/run/cos/state"
        if [ ! -f "${statemnt}/grub2/grub.cfg" ]; then
          statemnt="/run/initramfs/cos-state"
        fi

        # TODO this should be part of the elemental install command
        grub2-editenv ${statemnt}/grub_oem_env set state_label=COS_STATE
        grub2-editenv ${statemnt}/grub_oem_env set active_label=COS_ACTIVE
        grub2-editenv ${statemnt}/grub_oem_env set passive_label=COS_PASSIVE
        grub2-editenv ${statemnt}/grub_oem_env set recovery_label=COS_RECOVERY
        grub2-editenv ${statemnt}/grub_oem_env set system_label=COS_SYSTEM
        grub2-editenv ${statemnt}/grub_oem_env set oem_label=COS_OEM
  after-reset:
    - <<: *grubenv
  after-upgrade:
    # TODO labels should be parsed from state.yaml
    - <<: *grubenv
      if: '[ -f "/run/cos/grub_update_needed" ]'
