name: PR-x86_64
on:
 pull_request:
   paths:
     - conf/**
     - toolkit/**
     - tests/**
     - make/**
     - .github/**
     - Makefile
     - tests/**
concurrency:
  group: ci-PR-x86_64-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    env:
      FLAVOR: green
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow
      - name: Cached ISO
        id: cache-iso
        uses: actions/cache@v3
        env:
          cache-name: pr-iso-build
        with:
          path: ~/work/elemental-toolkit/elemental-toolkit/build/*.iso
          key: ${{ env.cache-name }}-${{ hashFiles('**/toolkit/**', '**/examples/**', '**/Makefile') }}
      - if: ${{ steps.cache-iso.outputs.cache-hit != 'true' }}
        name: Build toolkit
        run: |
          make build
      - if: ${{ steps.cache-iso.outputs.cache-hit != 'true' }}
        name: Build example OS
        run: |
          make build-example-os
      - if: ${{ steps.cache-iso.outputs.cache-hit != 'true' }}
        name: Build example ISO
        run: |
          make build-example-iso
  
  install-to-vm:
    runs-on: macos-12
    needs: build-x86_64
    env:
      FLAVOR: green
      ARCH: x86_64
      PACKER_LOG: 1
      PKR_VAR_accelerator: hvf
      PKR_VAR_cpus: 2
      PKR_VAR_machine_type: q35
    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow
      - name: Cached ISO
        id: cache-iso
        uses: actions/cache@v3
        env:
          cache-name: pr-iso-build
        with:
          path: ~/work/elemental-toolkit/elemental-toolkit/build/*.iso
          key: ${{ env.cache-name }}-${{ hashFiles('**/toolkit/**', '**/examples/**', '**/Makefile') }}
          fail-on-cache-miss: true
      - name: Cached Disk
        id: cache-disk
        uses: actions/cache@v3
        env:
          cache-name: pr-disk-build
        with:
          path: ~/work/elemental-toolkit/elemental-toolkit/build/*.qcow2
          key: ${{ env.cache-name }}-${{ hashFiles('**/toolkit/**', '**/examples/**', '**/Makefile') }}
      - if: ${{ steps.cache-disk.outputs.cache-hit != 'true' }}
        name: Install to disk with Packer
        run: |
          export PKR_VAR_firmware=$(find /usr/local/Cellar/qemu -name edk2-x86_64-code.fd -print -quit)
          make packer
  
  test-smoke:
    runs-on: macos-12
    needs: install-to-vm
    env:
      FLAVOR: green
      ARCH: x86_64
      ELMNTL_ACCEL: hvf
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - run: |
          git fetch --prune --unshallow
      - name: Cached Disk
        id: cache-disk
        uses: actions/cache@v3
        env:
          cache-name: pr-disk-build
        with:
          path: ~/work/elemental-toolkit/elemental-toolkit/build/*.qcow2
          key: ${{ env.cache-name }}-${{ hashFiles('**/toolkit/**', '**/examples/**', '**/Makefile') }}
          fail-on-cache-miss: true
      - name: Run VM script dependencies
        run: |
          brew install bash coreutils
      - name: Prepare test
        run: |
          export ELMNTL_FIRMWARE=$(find /usr/local/Cellar/qemu -name edk2-x86_64-code.fd -print -quit)
          make prepare-test
      - name: Run test-smoke
        run: |
          export GOPATH="/Users/runner/go"
          PATH=$PATH:$GOPATH/bin
          make test-smoke
      - name: Stop test VM
        if: always()
        run: |
          make test-clean

